pipeline:
  install:
    image: node:carbon
    commands:
      - npm install --quiet
    when:
      branch: [ master, develop, feature/* ]
      event: [ push, pull_request ]

  lint:
    image: node:carbon
    commands:
      - npm run lint
    when:
      branch: [ master, feature/* ]
      event: [ push, pull_request ]

  docker:
    image: plugins/docker
    repo: iknpx/steamx-api
    tags: latest
    secrets: [ docker_username, docker_password, steam_key ]
    build_args:
      - STEAM_KEY=$${STEAM_KEY}
    when:
      branch: [ master, develop ]
      event: [ push ]

  ssh:
    image: appleboy/drone-ssh
    pull: true
    host: 185.143.173.198
    user: root
    port: 22
    pull: true
    command_timeout: 3600
    secrets: [ ssh_key ]
    script:
      - cd /etc/api
      - sh deploy.sh
    when:
      branch: [ master, develop ]
      event: [push, tag, deployment]
