---
extends:
  - eslint:recommended

env:
  es6: true
  node: true

parserOptions:
  sourceType: module
  ecmaVersion: 8
  ecmaFeatures:
    experimentalObjectRestSpread: true

rules:
  comma-dangle: [2, always-multiline]
  indent: [2, 4]
  linebreak-style: [2, unix]
  no-console: 2
  quotes: [2, single]
  semi: [2, always]
