version: "2"
services:
  app:
    container_name: steamx-api
    restart: always
    build: .
    environment:
      - MONGODB_DB=steamx-api
      - MONGODB_HOST=mongodb://mongo
    ports:
      - 5000:5000
    links:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - /data:/data/db
